### ISSUE TITLE
custom GNN layer

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#89] opened 2021-04-19 11:35 UTC
here is the error I got after fixed  the ```observation_space``` in ```graph_observer.py```
```bash
Traceback (most recent call last):
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 88, in <module>
    app.run(run_configuration)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 70, in run_configuration
    init_gnn='init_interaction_network')
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/agents/graph_sac_agent.py", line 51, in __init__
    observer=observer)
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/agents/tfa_agent.py", line 45, in __init__
    self._agent = self.GetAgent(self._wrapped_env, params)
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/agents/graph_sac_agent.py", line 67, in GetAgent
    params=params
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/networks/network.py", line 98, in _capture_init
    init(self, **kwargs)
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/networks/gnn_actor_network.py", line 87, in __init__
    self._gnn = gnn(name=name, params=params)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 942, in __call__
    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3048, in _split_out_first_arg
    'The first argument to `Layer.call` must always be passed.')
ValueError: The first argument to `Layer.call` must always be passed.
  In call to configurable 'GNNActorNetwork' (<class 'bark_ml.library_wrappers.lib_tf_agents.networks.gnn_actor_network.GNNActorNetwork'>)
```
if any additional information is needed, please let me know. I really appreciate your time!

**Comment by patrickhart** [comment] 2021-04-19 12:53
I would recommend you to use the experiment runner example in which a GNN is fully integrated:
`bazel run //experiments:experiment_runner -- --exp_json=/ABSOLUTE_PATH/bark-ml/experiments/configs/phd/01_hyperparams/gnns/merging_large_embedding.json --mode=visualize` and see if you can visualize this.

If it works, I recommend you to train the same network and to observer its performance (whether it, e.g., learns).
After you made sure this works, you can step-by-step modify this file: https://github.com/bark-simulator/bark-ml/blob/master/bark_ml/library_wrappers/lib_tf_agents/networks/gnns/interaction_wrapper.py

It uses the approach proposed by Battaglia et al.: https://arxiv.org/abs/1806.01261
A variety of approaches should be possible using this framework.

**Comment by tinmodeHuang** [comment] 2021-04-20 09:34
the error was resolved by modifying as you suggested, and then the following error happend.
```bash
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
tf.Tensor([ 1 11  8  4], shape=(4,), dtype=int32) tf.Tensor([ 1 11  8  8], shape=(4,), dtype=int32) tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
Traceback (most recent call last):
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 88, in <module>
    app.run(run_configuration)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 78, in run_configuration
    runner.Train()
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/runners/tfa_runner.py", line 90, in Train
    self.CollectInitialEpisodes()
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/runners/tfa_runner.py", line 87, in CollectInitialEpisodes
    self._initial_collection_driver.run()
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 195, in run
    maximum_iterations=maximum_iterations)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/common.py", line 185, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 212, in _run
    self.env.time_step_spec())
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 717, in get_outer_shape
    nested_tensor, spec, num_outer_dims=num_outer_dims):
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 455, in is_batched_nested_tensors
    tf.nest.pack_sequence_as(specs, spec_shapes)))
ValueError: Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1.
Saw tensor_shapes:
   TimeStep(step_type=TensorShape([1]), reward=TensorShape([1]), discount=TensorShape([1]), observation=TensorShape([1, 1, 11, 361]))
And spec_shapes:
   TimeStep(step_type=TensorShape([]), reward=TensorShape([]), discount=TensorShape([]), observation=TensorShape([11, 361]))
```
where the observation is of multi-timesteps, its shape is (1, 11, 361).
I tried to turn the observation_spec into (1, 11, 361), but that caused a new error, so I expect your suggestions

**Comment by patrickhart** [comment] 2021-04-20 10:24
which command and script did you run? Would be useful for me to possibly reproduce the error. Did you use the virtual python environment and all the version specified in the `requirements.txt`?

**Comment by tinmodeHuang** [comment] 2021-04-20 11:33
run ```tfa_gnn.py``` with the command ```bazel run //examples:tfa_gnn -- --mode=train```.
yes, I did
it should be noted that ```the interaction_network``` was replaced with my custom network and the graph_observation.py was modified as well, so you may need those scripts to reproduce the error. If you really want to reproduce it for helping me, I'm glad to provide these scripts.

**Comment by patrickhart** [comment] 2021-04-20 12:57
Well, I first would recommend you to run the experiments using `bazel run //experiments:experiment_runner -- --exp_json=/ABSOLUTE_PATH/bark-ml/experiments/configs/phd/01_hyperparams/gnns/merging_large_embedding.json --mode=visualize`.

Then you can print out the exact shape that is required. Note: these vary during training and execution (due to the batch size).

**Comment by tinmodeHuang** [comment] 2021-04-21 02:20
Firstly, the experiments can be successfully run using``` bazel run //experiments:experiment_runner -- --exp_json=/ABSOLUTE_PATH/bark-ml/experiments/configs/phd/01_hyperparams/gnns/merging_large_embedding.json --mode=visualize```. 

Secondly, after ran ```bazel run //examples:tfa_gnn -- --mode=train``` successfully, I have implemented my custom GNN by modifying present ```interaction_wrapper```, but in the meanwhile I ran into the error above, I print out shapes of env.time_step_spec() and observation shown as (154,) and (1, 154) at the same time ```interaction_network``` working well. However, the error above was thrown after ```interaction_network``` was replaced with my custom GNN, at the point shapes of ```env.time_step_spec()``` and ```observation``` were (11, 361) and (1, 11, 361), I'm confused about the extra dimension ```1``` from the observation in ```Saw tensor_shapes```. if only I explain myself

**Comment by tinmodeHuang** [comment] 2021-04-21 06:32
thanks for your patience, the error was resolved by checking it several other times, the extra dimension arises from converting list of observation to tensor instead of array.

**Comment by patrickhart** [comment] 2021-04-21 07:14
Great that it works! If you have suggestions, new approaches and/or improvements for the architecture you are always welcome to contribute to this repository.

Will close this for now.

**Closed by patrickhart** 2021-04-21 07:14 UTC
